### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by HerrLindberg** [reyntjensw/Homey-FusionSolar#39]
Hi!

Same problem as the others.

Here is my diagnostic...

cd23ca43-f3bf-4e71-b4a8-c99c753d49f2

Regards Tobias

**Comment by reyntjensw** [comment]
good afternoon @HerrLindberg , you cannot use your email address to login into this system.
You must request an API user at your installer.

**Comment by HerrLindberg** [comment]
Still same problems.
Now with new user name...
Here is my diagnostic...

f0dbb750-e280-4958-af80-24b8a3-978efe

/L

**Comment by reyntjensw** [comment]
@HerrLindberg did you receive the username from your installer?
I do see that it is not returning systems.

In some cases the api access is not working because of a lack of permissions.

**Comment by HerrLindberg** [comment]
Hi!

Yes!

I have new username without any strange symbols etc.

What kind of permissions?

I´m the owner and do n ot have the installer rights...

/L

**Comment by HerrLindberg** [comment]
ps. I´m on this server...

https://region02eu5.fusionsolar.huawei.com/

**Comment by HerrLindberg** [comment]
https://region02eu5.fusionsolar.huawei.com/pvmswebsite/nologin/assets/build/index.html#/kiosk?kk=n7aKmJoCjbdM88uMCyoAE7A3DxyCq1no

**Comment by reyntjensw** [comment]
@HerrLindberg I do see that there are no systems connected to the api account.
Please ask your installer to double check.

**Comment by reyntjensw** [comment]
I have released a new version, can you please try again?

**Comment by HerrLindberg** [comment]
Still the same!

98fa632a-6247-4c4a-8d2d-838d7e524d77

Den ons 12 apr. 2023 21:07Wouter Reyntjens ***@***.***> skrev:

**Comment by reyntjensw** [comment]
Good evening
 
I still see the error  { failCode: 305, immediately: true, message: 'USER_MUST_RELOGIN'
 
Have you contacted Huawei about this?
 
Wouter

**Comment by reyntjensw** [comment]
In my case my account expired, they had to create a new account for me

**Comment by HerrLindberg** [comment]
Problem solved with new version!

Thanks for everything!

/T

Den tis 2 maj 2023 21:54Wouter Reyntjens ***@***.***> skrev:
